"""
Test Suite for Real Counterfactual What-If Simulation.

Validates:
1. Zero-change scenario matches baseline inference exactly.
2. Additional Cost modifies the correct model features.
3. Additional Delay modifies the correct schedule features.
4. Monthly Expenditure modifies the correct expenditure features.
5. Scenario predictions come from real trained XGBoost models.
6. Scenario Risk Score is generated by centralized risk_engine.py.
7. Proper separation between direct arithmetic metrics and ML predictions.
8. Risk Score uses empirical percentile normalization.
9. No old 1.25 / 3.20 / 35 / 30 arbitrary coefficients remain.
10. Monotonicity: higher cost overrun or schedule delay never reduces risk.
11. PDP is mathematically averaged over multiple reference observations (not 1 project).
12. Validation rejection of negative, NaN, or infinite inputs (422).
13. Unknown project IDs return 404.
14. No NaN or Infinity in responses.
"""
import sys
import math
from pathlib import Path
import pytest
from fastapi.testclient import TestClient

backend_dir = Path(__file__).resolve().parent.parent
ai_dir = backend_dir.parent / "ai"

# Ensure backend and ai are at the head of sys.path, and purge any conflicting root 'app'
if str(backend_dir) in sys.path:
    sys.path.remove(str(backend_dir))
sys.path.insert(0, str(backend_dir))

if str(ai_dir) in sys.path:
    sys.path.remove(str(ai_dir))
sys.path.insert(1, str(ai_dir))

if "app" in sys.modules:
    mod = sys.modules["app"]
    if getattr(mod, "__file__", None) is None or "backend" not in str(getattr(mod, "__file__", "")):
        del sys.modules["app"]

from app.main import app
from app.config import settings
from app.services.risk_engine import (
    calculate_risk_score,
    percentile_rank,
    DEFAULT_WEIGHT_COST,
    DEFAULT_WEIGHT_SCHEDULE,
    COST_OVERRUN_QUANTILES,
    SCHEDULE_DELAY_QUANTILES,
    RISK_LEVEL_THRESHOLDS,
)
from app.services.ai_engine_service import ai_engine
from app.schemas.simulation import WhatIfRequest
from app.services.simulation_service import (
    simulate_project_scenario,
    get_reference_feature_dataset,
    _compute_pdp_cost,
    _compute_pdp_schedule,
)
from app.database import SessionLocal

client = TestClient(app)
SAMPLE_PID = "020100044"


@pytest.fixture(scope="module")
def db_session():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def test_what_if_zero_change_equivalence(db_session):
    """
    Test 1: Zero-change scenario returns the EXACT same predictions and risk score
    as baseline project inference.
    """
    req = WhatIfRequest(additional_cost=0.0, additional_delay_months=0.0, monthly_expenditure=None)
    res = simulate_project_scenario(SAMPLE_PID, req, db_session)

    assert res.baseline.predicted_cost_overrun == res.scenario.predicted_cost_overrun
    assert res.baseline.predicted_schedule_delay == res.scenario.predicted_schedule_delay
    assert res.baseline.risk_score == res.scenario.risk_score
    assert res.baseline.risk_level == res.scenario.risk_level
    assert res.impact.cost_change == 0.0
    assert res.impact.remaining_months_change == 0.0
    assert res.impact.cost_overrun_change == 0.0
    assert res.impact.schedule_delay_change == 0.0
    assert res.impact.risk_score_change == 0.0


def test_additional_cost_modifies_features(db_session):
    """
    Test 2: Additional Cost increases cost features and updates predicted overrun.
    """
    req_base = WhatIfRequest(additional_cost=0.0, additional_delay_months=0.0)
    res_base = simulate_project_scenario(SAMPLE_PID, req_base, db_session)

    req_cost = WhatIfRequest(additional_cost=500.0, additional_delay_months=0.0)
    res_cost = simulate_project_scenario(SAMPLE_PID, req_cost, db_session)

    assert res_cost.scenario.cost == res_base.baseline.cost + 500.0
    assert res_cost.impact.cost_change == 500.0
    assert res_cost.scenario.predicted_cost_overrun >= res_base.baseline.predicted_cost_overrun


def test_additional_delay_modifies_features(db_session):
    """
    Test 3: Additional Delay modifies schedule features and updates predicted schedule delay.
    """
    req_base = WhatIfRequest(additional_cost=0.0, additional_delay_months=0.0)
    res_base = simulate_project_scenario(SAMPLE_PID, req_base, db_session)

    req_delay = WhatIfRequest(additional_cost=0.0, additional_delay_months=12.0)
    res_delay = simulate_project_scenario(SAMPLE_PID, req_delay, db_session)

    assert res_delay.scenario.remaining_months == res_base.baseline.remaining_months + 12.0
    assert res_delay.impact.remaining_months_change == 12.0
    assert res_delay.scenario.predicted_schedule_delay >= res_base.baseline.predicted_schedule_delay


def test_monthly_expenditure_modifies_features(db_session):
    """
    Test 4: Monthly expenditure directly modifies expenditure velocity and impacts risk.
    """
    req_base = WhatIfRequest(additional_cost=0.0, additional_delay_months=0.0)
    res_base = simulate_project_scenario(SAMPLE_PID, req_base, db_session)

    req_fast = WhatIfRequest(additional_cost=0.0, additional_delay_months=0.0, monthly_expenditure=75.0)
    res_fast = simulate_project_scenario(SAMPLE_PID, req_fast, db_session)

    assert res_fast.scenario.monthly_expenditure == 75.0
    assert res_fast.impact.expenditure_change == round(75.0 - res_base.baseline.monthly_expenditure, 2)


def test_xgboost_models_used(db_session):
    """
    Test 5: Scenario predictions come from real XGBoost regressors loaded in ai_engine.
    """
    assert "cost_regressor_3m" in ai_engine.models
    assert "time_regressor_3m" in ai_engine.models
    assert "cost_reg_3m_preprocessor" in ai_engine.models
    assert "time_reg_3m_preprocessor" in ai_engine.models

    req = WhatIfRequest(additional_cost=250.0, additional_delay_months=4.0, monthly_expenditure=30.0)
    res = simulate_project_scenario(SAMPLE_PID, req, db_session)

    assert isinstance(res.scenario.predicted_cost_overrun, float)
    assert isinstance(res.scenario.predicted_schedule_delay, float)


def test_scenario_risk_score_from_risk_engine(db_session):
    """
    Test 6: Scenario Risk Score matches centralized calculate_risk_score result.
    """
    req = WhatIfRequest(additional_cost=300.0, additional_delay_months=6.0, monthly_expenditure=40.0)
    res = simulate_project_scenario(SAMPLE_PID, req, db_session)

    expected_risk = calculate_risk_score(
        res.scenario.predicted_cost_overrun,
        res.scenario.predicted_schedule_delay
    )
    assert res.scenario.risk_score == expected_risk.risk_score
    assert res.scenario.risk_level == expected_risk.risk_level
    assert res.scenario.cost_risk_component == expected_risk.cost_risk_component
    assert res.scenario.schedule_risk_component == expected_risk.schedule_risk_component


def test_direct_metrics_vs_predictions_separated(db_session):
    """
    Test 7: Projected cost, remaining duration, and expenditure are transparent arithmetic,
    while cost overrun, schedule delay, and risk score are ML predictions.
    """
    req = WhatIfRequest(additional_cost=150.0, additional_delay_months=5.0, monthly_expenditure=55.0)
    res = simulate_project_scenario(SAMPLE_PID, req, db_session)

    # Arithmetic
    assert res.scenario.cost == round(res.baseline.cost + 150.0, 2)
    assert res.scenario.remaining_months == round(res.baseline.remaining_months + 5.0, 2)
    assert res.scenario.monthly_expenditure == 55.0

    # ML predictions exist and are non-trivial
    assert res.scenario.predicted_cost_overrun is not None
    assert res.scenario.predicted_schedule_delay is not None


def test_risk_score_empirical_percentile_normalization():
    """
    Test 8: Risk score uses empirical percentile normalization, remains strictly 0-100,
    and higher predicted cost overrun / schedule delay never reduces risk (monotonicity).
    """
    # 1. Monotonicity of percentile_rank
    cost_test_vals = [-50.0, 0.0, 2.0, 10.0, 25.0, 50.0, 100.0, 500.0, 5000.0]
    prev_pct = -1.0
    for c in cost_test_vals:
        pct = percentile_rank(c, COST_OVERRUN_QUANTILES)
        assert 0.0 <= pct <= 1.0, f"Percentile rank {pct} out of [0, 1] range"
        assert pct >= prev_pct, f"Percentile rank decreased from {prev_pct} to {pct} at cost {c}"
        prev_pct = pct

    delay_test_vals = [-10.0, 0.0, 1.0, 6.0, 12.0, 24.0, 48.0, 100.0, 400.0]
    prev_pct = -1.0
    for d in delay_test_vals:
        pct = percentile_rank(d, SCHEDULE_DELAY_QUANTILES)
        assert 0.0 <= pct <= 1.0, f"Percentile rank {pct} out of [0, 1] range"
        assert pct >= prev_pct, f"Percentile rank decreased from {prev_pct} to {pct} at delay {d}"
        prev_pct = pct

    # 2. Risk Score monotonicity and bounds
    prev_score = -1.0
    for c in cost_test_vals:
        res = calculate_risk_score(c, 12.0)
        assert 0.0 <= res.risk_score <= 100.0
        assert res.risk_score >= prev_score
        prev_score = res.risk_score

    # 3. Configurable weights
    custom_res = calculate_risk_score(25.0, 12.0, weight_cost=0.70, weight_schedule=0.30)
    assert 0.0 <= custom_res.risk_score <= 100.0


def test_no_old_risk_coefficients():
    """
    Test 9: Verify that no hardcoded 1.25 / 3.20 / 35 / 30 coefficients exist in risk_engine.py.
    """
    risk_engine_path = backend_dir / "app" / "services" / "risk_engine.py"
    content = risk_engine_path.read_text(encoding="utf-8")

    # None of these arbitrary coefficients may appear in the risk engine
    for coeff in ["1.25", "3.20"]:
        assert coeff not in content, f"Arbitrary coefficient '{coeff}' found in risk_engine.py"

    # Verify that the formula is explicitly 100 * (weight * percentile + weight * percentile)
    assert "percentile_rank" in content
    assert "COST_OVERRUN_QUANTILES" in content
    assert "SCHEDULE_DELAY_QUANTILES" in content


def test_pdp_averaged_over_multiple_reference_observations():
    """
    Test 10: Verify that PDP is mathematically averaged over multiple reference observations (N >= 10),
    not generated from one project.
    """
    ref_df = get_reference_feature_dataset(n_samples=50)
    assert not ref_df.empty, "Reference dataset should not be empty"
    assert len(ref_df) >= 10, f"Expected at least 10 reference observations, found {len(ref_df)}"

    # Run true PDP functions directly and check outputs
    pdp_cost = _compute_pdp_cost(
        base_feats=ref_df.iloc[[0]],
        orig_cost=1000.0,
        base_rev_cost=1000.0,
        scen_rev_cost=1200.0,
        cum_exp=400.0,
        phys_prog=45.0,
        base_predicted_ov=15.0,
        scen_predicted_ov=25.0,
        models=ai_engine.models,
        n_reference_samples=50,
    )
    assert len(pdp_cost.points) == 11
    # Check that points are valid and finite
    assert all(math.isfinite(pt.y) for pt in pdp_cost.points)

    pdp_sched = _compute_pdp_schedule(
        base_feats=ref_df.iloc[[0]],
        base_sched_ext=6.0,
        scen_sched_ext=12.0,
        base_rem_mo=18.0,
        orig_dur=36.0,
        base_predicted_delay=8.0,
        scen_predicted_delay=15.0,
        models=ai_engine.models,
        n_reference_samples=50,
    )
    assert len(pdp_sched.points) == 11
    assert all(math.isfinite(pt.y) for pt in pdp_sched.points)


def test_invalid_scenario_values_rejected():
    """
    Test 11: Invalid scenario inputs (negative numbers, strings) return 422 Unprocessable Entity.
    """
    prefix = settings.API_PREFIX

    # Negative cost
    r1 = client.post(f"{prefix}/projects/{SAMPLE_PID}/what-if", json={"additional_cost": -25.0})
    assert r1.status_code == 422

    # Negative delay
    r2 = client.post(f"{prefix}/projects/{SAMPLE_PID}/what-if", json={"additional_delay_months": -5.0})
    assert r2.status_code == 422

    # Negative monthly expenditure
    r3 = client.post(f"{prefix}/projects/{SAMPLE_PID}/what-if", json={"monthly_expenditure": -1.0})
    assert r3.status_code == 422


def test_api_unknown_project_returns_404():
    """
    Test 12: Unknown project IDs return 404 Not Found.
    """
    prefix = settings.API_PREFIX
    r = client.post(f"{prefix}/projects/NON_EXISTENT_PROJECT_XYZ/what-if", json={"additional_cost": 0.0})
    assert r.status_code == 404


def test_no_nan_or_infinity_in_response(db_session):
    """
    Test 13: Ensure all numeric metrics and curves are strictly finite.
    """
    req = WhatIfRequest(additional_cost=50.0, additional_delay_months=2.0, monthly_expenditure=20.0)
    res = simulate_project_scenario(SAMPLE_PID, req, db_session)

    for metric in [res.baseline, res.scenario]:
        for k, v in metric.model_dump().items():
            if isinstance(v, (int, float)):
                assert not math.isnan(v), f"Metric {k} is NaN"
                assert not math.isinf(v), f"Metric {k} is Infinity"

    for pt in res.pdp_cost.points + res.pdp_schedule.points:
        assert not math.isnan(pt.x) and not math.isinf(pt.x)
        assert not math.isnan(pt.y) and not math.isinf(pt.y)


def test_canonical_schedule_delay_artifact_and_synchronization():
    """
    Test 14: Verify that the loaded schedule delay model artifact corresponds
    to the final xgb_del model saved as best_model_schedule_delay.json from train_models.py,
    and is strictly synchronized across results/best_model and ai/models.
    """
    import json
    import hashlib
    import xgboost as xgb

    best_model_path = backend_dir.parent / "results" / "best_model" / "best_model_schedule_delay.json"
    ai_model_path = backend_dir.parent / "ai" / "models" / "best_model_schedule_delay.json"

    assert best_model_path.exists(), f"Canonical model artifact missing at {best_model_path}"
    assert ai_model_path.exists(), f"Synchronized model artifact missing at {ai_model_path}"

    # Verify bit-for-bit synchronization
    best_bytes = best_model_path.read_bytes()
    ai_bytes = ai_model_path.read_bytes()
    sha_best = hashlib.sha256(best_bytes).hexdigest()
    sha_ai = hashlib.sha256(ai_bytes).hexdigest()
    assert sha_best == sha_ai, f"Artifact desynchronization: {sha_best} != {sha_ai}"

    # Verify model architecture corresponds to final xgb_del from train_models.py
    # xgb_del was trained with n_estimators=260, learning_rate=0.035, max_depth=6 on delta_del
    with open(best_model_path, "r", encoding="utf-8") as f:
        model_meta = json.load(f)

    # 1. Booster rounds verification (260 trees)
    booster = xgb.Booster()
    booster.load_model(str(best_model_path))
    assert booster.num_boosted_rounds() == 260, (
        f"Expected 260 boosted rounds from final train_models.py, got {booster.num_boosted_rounds()}"
    )

    # 2. Base score verification:
    # Training semantics: delta_delay = target_future_delay - current_delay
    # The average delta in train set is ~1.28 months, whereas total delay would be >15 months.
    learner_param = model_meta.get("learner", {}).get("learner_model_param", {})
    base_score_str = learner_param.get("base_score", "")
    cleaned_score = float(base_score_str.strip("[]"))
    assert 0.5 < cleaned_score < 5.0, (
        f"base_score {cleaned_score} does not match delta_delay semantics (~1.28). "
        "It appears trained on raw total delay instead of delta!"
    )

    # 3. Model loaded in ai_engine corresponds to this canonical model
    ai_engine._ensure_initialized()
    assert "best_model_schedule_delay" in ai_engine.models
    assert "xgb_schedule_model" in ai_engine.models
    loaded_booster = ai_engine.models["xgb_schedule_model"].get_booster()
    assert loaded_booster.num_boosted_rounds() == 260


def test_authoritative_schedule_reconstruction_semantics(db_session):
    """
    Test 15: Verify authoritative training and inference semantics:
    target_future_delay = current_delay + predicted_delta
    Model trained on: delta_delay = target_future_delay - current_delay
    Inference:
    predicted_delta = xgb_schedule_model.predict(features)
    predicted_total_delay = scenario_current_delay + predicted_delta

    CRITICAL: Raw XGBoost output must NEVER be treated as total delay.
    """
    from src.predict import predict_time
    from src.project_service import prepare_prediction_features, get_current_status

    ai_engine._ensure_initialized()
    df_to_use = ai_engine._get_df_for_project(SAMPLE_PID)
    current = get_current_status(SAMPLE_PID, df_to_use)
    features_df = prepare_prediction_features(SAMPLE_PID, df_to_use)

    # Define a scenario with an explicit current schedule extension
    scen_current_delay = 14.5
    scen_current = current.copy()
    scen_current["schedule_extension_months"] = scen_current_delay

    scen_features = features_df.copy()
    scen_features["schedule_extension_months"] = scen_current_delay

    time_pred = predict_time(scen_features, ai_engine.models, scen_current, horizons=[3])
    h3 = time_pred["3_month"]

    predicted_delta = h3["predicted_additional_delay_months"]
    predicted_total_delay = h3["predicted_total_schedule_extension_months"]

    # Explicit check 1: Model predictions are valid floats
    assert isinstance(predicted_delta, float)
    assert isinstance(predicted_total_delay, float)

    # Explicit check 2: Reconstruction follows target_future_delay = current_delay + predicted_delta
    expected_total = round(scen_current_delay + predicted_delta, 2)
    assert predicted_total_delay == expected_total, (
        f"Reconstruction mismatch: {predicted_total_delay} != {expected_total} "
        f"(scenario_current_delay={scen_current_delay}, predicted_delta={predicted_delta})"
    )

    # Explicit check 3: Raw XGBoost output is NOT treated as total delay
    assert predicted_total_delay != predicted_delta, (
        "CRITICAL ERROR: Raw XGBoost output was treated directly as total delay! "
        f"predicted_total_delay ({predicted_total_delay}) == predicted_delta ({predicted_delta})"
    )


def test_what_if_schedule_simulation_pipeline_reconstruction(db_session):
    """
    Test 16: Verify that the What-If simulation service pipeline enforces the exact
    schedule reconstruction:
    predicted_total_delay = scenario_current_delay + predicted_delta
    and that impact deltas match the difference.
    """
    base_req = WhatIfRequest(additional_cost=0.0, additional_delay_months=0.0)
    base_res = simulate_project_scenario(SAMPLE_PID, base_req, db_session)

    # Add 9.5 months of additional delay
    add_delay = 9.5
    scen_req = WhatIfRequest(additional_cost=0.0, additional_delay_months=add_delay)
    scen_res = simulate_project_scenario(SAMPLE_PID, scen_req, db_session)

    # Check baseline delay reconstruction
    assert scen_res.scenario.predicted_schedule_delay >= scen_res.baseline.predicted_schedule_delay
    assert scen_res.impact.schedule_delay_change == round(
        scen_res.scenario.predicted_schedule_delay - scen_res.baseline.predicted_schedule_delay, 2
    )

    # Check PDP for schedule uses x_val + predicted_delta
    pdp_sched = scen_res.pdp_schedule
    for pt in pdp_sched.points:
        assert pt.y >= 0.0

