"""initial_database_schema

Revision ID: e372f347803e
Revises: 
Create Date: 2026-08-30 02:09:34.377709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e372f347803e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('ministries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ministries_code'), 'ministries', ['code'], unique=False)
    op.create_index(op.f('ix_ministries_id'), 'ministries', ['id'], unique=False)
    op.create_index(op.f('ix_ministries_name'), 'ministries', ['name'], unique=True)
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_code'), 'sectors', ['code'], unique=False)
    op.create_index(op.f('ix_sectors_id'), 'sectors', ['id'], unique=False)
    op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('project_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('implementing_agency', sa.String(length=255), nullable=True),
    sa.Column('contractor', sa.String(length=255), nullable=True),
    sa.Column('phase', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('project_status', sa.String(length=50), nullable=False),
    sa.Column('schedule_status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('original_completion_date', sa.Date(), nullable=True),
    sa.Column('expected_completion_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('project_age_months', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('schedule_extension_months', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('original_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('revised_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cumulative_expenditure', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_overrun_pct', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_escalation_crore', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expenditure_ratio_pct', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('physical_progress', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('physical_progress_target', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('financial_progress', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('cost_risk', sa.Integer(), nullable=False),
    sa.Column('time_risk', sa.Integer(), nullable=False),
    sa.Column('impl_risk', sa.Integer(), nullable=False),
    sa.Column('overall_risk', sa.Integer(), nullable=False),
    sa.Column('source_report', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_implementing_agency'), 'projects', ['implementing_agency'], unique=False)
    op.create_index(op.f('ix_projects_ministry_id'), 'projects', ['ministry_id'], unique=False)
    op.create_index('ix_projects_ministry_sector', 'projects', ['ministry_id', 'sector_id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=False)
    op.create_index(op.f('ix_projects_project_status'), 'projects', ['project_status'], unique=False)
    op.create_index(op.f('ix_projects_risk_level'), 'projects', ['risk_level'], unique=False)
    op.create_index(op.f('ix_projects_risk_score'), 'projects', ['risk_score'], unique=False)
    op.create_index(op.f('ix_projects_schedule_status'), 'projects', ['schedule_status'], unique=False)
    op.create_index(op.f('ix_projects_sector_id'), 'projects', ['sector_id'], unique=False)
    op.create_index(op.f('ix_projects_state'), 'projects', ['state'], unique=False)
    op.create_index('ix_projects_status_risk', 'projects', ['schedule_status', 'risk_level'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    op.create_table('project_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('reporting_date', sa.Date(), nullable=False),
    sa.Column('report_month_str', sa.String(length=20), nullable=True),
    sa.Column('physical_progress', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('financial_progress', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('cumulative_expenditure', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revised_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_overrun_pct', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('schedule_extension_months', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overdue_days', sa.Integer(), nullable=False),
    sa.Column('schedule_status', sa.String(length=50), nullable=True),
    sa.Column('physical_progress_delta_1m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cost_overrun_delta_1m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expenditure_ratio_delta_1m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('risk_signal_count', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'reporting_date', name='uq_project_reporting_date')
    )
    op.create_index('ix_project_progress_date', 'project_progress', ['project_id', 'reporting_date'], unique=False)
    op.create_index(op.f('ix_project_progress_id'), 'project_progress', ['id'], unique=False)
    op.create_index(op.f('ix_project_progress_project_id'), 'project_progress', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_progress_reporting_date'), 'project_progress', ['reporting_date'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('prediction_date', sa.DateTime(), nullable=False),
    sa.Column('as_of_month', sa.Date(), nullable=True),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('cost_overrun_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('time_overrun_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('predicted_additional_overrun_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('predicted_additional_cost_crore', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('predicted_final_cost_overrun_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('predicted_final_revised_cost_crore', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('predicted_additional_delay_months', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('predicted_total_schedule_extension_months', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tentative_completion_date', sa.String(length=50), nullable=True),
    sa.Column('estimated_time_needed', sa.String(length=100), nullable=True),
    sa.Column('top_risk_drivers', sa.JSON(), nullable=True),
    sa.Column('top_protective_factors', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_predictions_id'), 'risk_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_risk_predictions_prediction_date'), 'risk_predictions', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_risk_predictions_project_id'), 'risk_predictions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_predictions_project_id'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_prediction_date'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_id'), table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_index(op.f('ix_project_progress_reporting_date'), table_name='project_progress')
    op.drop_index(op.f('ix_project_progress_project_id'), table_name='project_progress')
    op.drop_index(op.f('ix_project_progress_id'), table_name='project_progress')
    op.drop_index('ix_project_progress_date', table_name='project_progress')
    op.drop_table('project_progress')
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index('ix_projects_status_risk', table_name='projects')
    op.drop_index(op.f('ix_projects_state'), table_name='projects')
    op.drop_index(op.f('ix_projects_sector_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_schedule_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_risk_score'), table_name='projects')
    op.drop_index(op.f('ix_projects_risk_level'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index('ix_projects_ministry_sector', table_name='projects')
    op.drop_index(op.f('ix_projects_ministry_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_implementing_agency'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_id'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_code'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_ministries_name'), table_name='ministries')
    op.drop_index(op.f('ix_ministries_id'), table_name='ministries')
    op.drop_index(op.f('ix_ministries_code'), table_name='ministries')
    op.drop_table('ministries')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
