"""increase_numeric_precision

Revision ID: f50e78d20323
Revises: e372f347803e
Create Date: 2026-08-30 02:13:59.492010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50e78d20323'
down_revision: Union[str, None] = 'e372f347803e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_progress', 'physical_progress',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('project_progress', 'financial_progress',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('project_progress', 'cumulative_expenditure',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('project_progress', 'revised_cost',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('project_progress', 'cost_overrun_pct',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('project_progress', 'schedule_extension_months',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('project_progress', 'physical_progress_delta_1m',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=True)
    op.alter_column('project_progress', 'cost_overrun_delta_1m',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=True)
    op.alter_column('project_progress', 'expenditure_ratio_delta_1m',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=True)
    op.alter_column('projects', 'project_age_months',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('projects', 'schedule_extension_months',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'original_cost',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('projects', 'revised_cost',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('projects', 'cumulative_expenditure',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'cost_overrun_pct',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'cost_escalation_crore',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'expenditure_ratio_pct',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'physical_progress',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'physical_progress_target',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'financial_progress',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('risk_predictions', 'cost_overrun_probability',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'time_overrun_probability',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_additional_overrun_pct',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_additional_cost_crore',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_final_cost_overrun_pct',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_final_revised_cost_crore',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_additional_delay_months',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_total_schedule_extension_months',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_predictions', 'predicted_total_schedule_extension_months',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_additional_delay_months',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_final_revised_cost_crore',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_final_cost_overrun_pct',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_additional_cost_crore',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'predicted_additional_overrun_pct',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'time_overrun_probability',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('risk_predictions', 'cost_overrun_probability',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('projects', 'financial_progress',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'physical_progress_target',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'physical_progress',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'expenditure_ratio_pct',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'cost_escalation_crore',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'cost_overrun_pct',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'cumulative_expenditure',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'revised_cost',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('projects', 'original_cost',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('projects', 'schedule_extension_months',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('projects', 'project_age_months',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('project_progress', 'expenditure_ratio_delta_1m',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('project_progress', 'cost_overrun_delta_1m',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('project_progress', 'physical_progress_delta_1m',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('project_progress', 'schedule_extension_months',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('project_progress', 'cost_overrun_pct',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('project_progress', 'revised_cost',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('project_progress', 'cumulative_expenditure',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('project_progress', 'financial_progress',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('project_progress', 'physical_progress',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
